config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  resources :users do 
    member do
      get :following, :followers
    end
  end
  resources :relationships
  root "pages#index"
  resources :posts
  get '/home', to: 'pages#home'
  get 'user/:id', to: 'pages#profile', as: :profile
  get 'explore', to: "pages#explore"  
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :user

  validates :user_id, presence: true
  validates :content, presence: true, length: {maximum:140}

  default_scope { order(created_at: :desc) }
end

app/models/relationship.rb
class Relationship < ApplicationRecord
  belongs_to :follower, class_name: "User"
  belongs_to :followed, class_name: "User"

  validates :follower_id, presence: true
  validates :followed_id, presence: true

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :posts, dependent: :destroy

  has_many :active_relationships, class_name: "Relationship", foreign_key:    "follower_id", dependent: :destroy
  has_many :passive_relationships, class_name: "Relationship", foreign_key:    "followed_id", dependent: :destroy

  has_many :following, through: :active_relationships, source: :followed
  has_many :followers, through: :passive_relationships, source: :follower

  # helper methods

  # follow another user
  def follow(other)
    active_relationships.create!(followed_id: other.id)
  end

  # unfollow a user
  def unfollow(other)
    active_relationships.find_by(followed_id: other.id).destroy
  end

  # is following a user
  def following?(other)
    following.include?(other)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :profile_info

  private
  def profile_info
    if params[:id]
      @user_profile = User.find_by_username(params[:id])
    end
  end

end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  before_action :set_to_follow
  def index
  end
  
  def home
    @posts = Post.all
    if user_signed_in?
      @newPost = current_user.posts.build
    end
  end

  def profile
    # grap the username from the URL
    if(User.find_by_username(params[:id]))
      @username = params[:id]
      @posts = Post.all.where("user_id = ?", User.find_by_username(params[:id]).id)
      @newPost = Post.new
    else
      # redirect to 404 (root for now)
      redirect_to root_path, notice: 'User not found'
    end

  end
  
  def explore
    @posts = Post.all
    @newPost = current_user.posts.build if user_signed_in?
  end

  private 
    def set_to_follow
      if user_signed_in?
        current_username = current_user.username
        @toFollow = User.where.not(username: current_username)
      end
    end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
   # GET /tweets/new
   def new
      @post = current_user.posts.build
   end

  # POST /tweets
  # POST /tweets.json
  def create
    @post = current_user.posts.build(post_params)

    respond_to do |format|
      if @post.save
        format.html { redirect_to "", notice: 'Smart idea was successfully created.' }
      else
        format.html { redirect_to "", notice: 'Smart idea was not created.' }
      end
    end
  end

  private
 

  # Only allow a list of trusted parameters through.
  def post_params
    params.require(:post).permit(:user_id, :content)
  end
end

app/controllers/registrations_controller.rb
class RegistrationsController < Devise::RegistrationsController
  private

    def sign_up_params
      params.require(:user).permit(:username, :email, :password, :password_confirmation, :remember_me)
    end

    def account_update_params
      params.require(:user).permit(:username, :email, :password, :password_confirmation, :current_password)
    end
end

app/controllers/relationships_controller.rb
class RelationshipsController < ApplicationController

  def create
    # user = User.find_username(params[:id])
    # debugger
    user = User.find(params[:followed_id].keys[0])
    current_user.follow(user)
    redirect_to profile_path(current_user.username)
  end
  
  def destroy
    user = Relationship.find(params[:id]).followed 
    current_user.unfollow(user)
    redirect_to profile_path(current_user.username)
  end
  
end

app/helpers/application_helper.rb
module ApplicationHelper
  def gravatar_for(user, options = {size: 50})
    if user
      gravatar_id = Digest::MD5::hexdigest(user.email.downcase)
      size = options[:size]
      gravatar_url = "https://secure.gravatar.com/avatar/#{gravatar_id}?s=#{size}"
      image_tag(gravatar_url, alt: user.username, class: "rounded-circle")
    end
  end
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/site_helper.rb
module SiteHelper
  def user_or_guest
    if user_signed_in?
      render '/layouts/navbar_user'
    else
      render '/layouts/navbar_guest'
    end
  end

  def landing_page
    if user_signed_in? 
      controller.redirect_to home_path
    else 
      render '/pages/guest_landing'
    end 
  end

  def add_new_post
    if user_signed_in? 
      render '/components/post_form'
    end
  end

end

app/views/layouts/_navbar.html.erb
<div class="container my-0">
  <%= user_or_guest%>
</div>

app/views/layouts/_navbar_guest.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-white border-bottom mb-4">
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item">
        <%= link_to 'Home', home_path, class: 'nav-link'%>
      </li>
      <li class="nav-item">
         <%= link_to 'Moments', explore_path, class: 'nav-link'%>
      </li>
    </ul>

    <div class="nav navbar-nav">
      <div class="nav-item dropdown">
        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          Guest
        </a>
        <div class="dropdown-menu" aria-labelledby="navbarDropdown">
          <a class="dropdown-item" href="#">Help</a>
          <div class="dropdown-divider"></div>
          <%= link_to 'Sign Up', new_user_registration_path, class: 'dropdown-item'%>
          <div class="dropdown-divider"></div>
          <%= link_to 'Sign In', new_user_session_path, class: 'dropdown-item'%>
        </div>
      </div>
    </div>
  </div>
</nav>

app/views/layouts/_navbar_user.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-white border-bottom mb-0">
  <div class="logo-container"><p>Smart </p><%= image_tag('smart-idea-logo3.png') %></div>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto ml-5">
      <li class="nav-item">
        <%= link_to 'Home', home_path, class: 'nav-link'%>
      </li>
      <li class="nav-item">
         <%= link_to 'Moments', explore_path, class: 'nav-link'%>
      </li>
      <li class="nav-item">
        <%= link_to 'Messages', home_path, class: 'nav-link'%>
      </li>
      <li class="nav-item">
        <%= link_to 'Notifications', home_path, class: 'nav-link'%>
      </li>
    </ul>

    <div class="nav navbar-nav">

      <form class="form-inline my-2 my-lg-0">
        <input class="form-control mr-sm-2" type="search" placeholder="Search Smart Idea" aria-label="Search">
        <button class="btn btn-light my-2 my-sm-0" type="submit">Search</button>
      </form>
      
      <div class="nav-item dropdown">
        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          <%= current_user.username%>
        </a>
        <div class="dropdown-menu" aria-labelledby="navbarDropdown">
          <%= link_to 'Profile', profile_path(current_user.username), class: 'dropdown-item'%>
          <div class="dropdown-divider"></div>
          <a class="dropdown-item" href="#">Help</a>
          <div class="dropdown-divider"></div>
          <%= link_to 'Edit Profile', edit_user_registration_path, class: "dropdown-item"%>
          <div class="dropdown-divider"></div>
          <%= link_to 'Logout', destroy_user_session_path, method: :delete, class: "dropdown-item"%>
        </div>

      </div>
        <div class="nav-item">
          <a class="btn btn-primary btn-sm" href="#">Add Post</a>
        </div>

    </div>

  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Smartidea</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <link href="https://fonts.googleapis.com/css2?family=Roboto:wght@400;700&family=Source+Sans+Pro:wght@600&display=swap" rel="stylesheet">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.1/css/all.min.css" integrity="sha512-+4zCK9k+qNFUR5X+cKL9EIR+ZOhtIloNl9GIKS57V1MyNsYpYcUrUeQc9vNfzsWfV28IaLL3i96P9sdNyeRssA==" crossorigin="anonymous" />
    <%= stylesheet_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body id="top">
    <%= render '/layouts/navbar'%>

   <% 
=begin %>  <% ruby_code %>
      <% if user_signed_in? %>
        <div class="profile-banner my-0">
          <%= image_tag('profile-banner')%>
        </div>
      <% end %>
    <% 
=end %>
<% if params[:id] != nil && @user_profile %>
  <% @URL = "/user/#{params[:id]}"%>
  <% if current_page?(@URL)%>
    <div class="profile-banner mt-0 ">
          <%= image_tag('profile-banner')%>
    </div>
    <div class="container mt-3">
      <div class="row text-center">
        <div class="col-2">
          <% if @user_profile %>
            <div class="card border-0" style="width: 100%;">
              <div class="card-body d-flex flex-column mx-auto p-0 profile-info">
                <div class="mt-0">
                  <%= gravatar_for(@user_profile)%>
                </div>
                <div class="profile-username">
                  <p>@<%= @user_profile.username%></p>
                </div>
              </div>
            </div>
          <% end %>
        </div>
        <div class="col-4 ml-4 pl-0 d-flex">
          <div class="mr-4">Smart Ideas <br>
            <h6 class="text-left text-primary">18</h6>
          </div>
          <div>Followers <br>
            <h6 class="text-left text-primary">10.8K</h6>
          </div>
        </div>
        <div class="col-4 pr-4">
           <%= link_to 'Edit Profile', edit_user_registration_path, class: "btn btn-outline-info float-right mr-4"%>
        </div>
      </div>
    </div>
  <% end %>
<% end %>

    <div class="container-fluid">
      <span class="notice"><%= notice %></span>
      <span class="alert"><%= alert %></span>
      <%= yield %>
    </div>
  </body>
</html>

app/views/pages/_guest_landing.html.erb
<div class="guest-landing row container  mx-auto justify-content-center">
  <div class="col-sm-5">
    <div class="container-guest">
      <h1 class="text-white">Welcome to Smart Idea</h1>
      <p class="guest-text text-white">Connect with smart buddies. Chat with new friends. Share your ideas succintly and eloquently. Just like a smart idea but with crisp & concise words</p>
    </div>
  </div>
  <div class="col-sm-5">
    <div class="card login-card border-0">

    </div>

    <div class="card signup-card border-0 mt-4">

    </div>
  </div>
  <div class="col-12 text-center text-white guest-footer mx-0">
    <p>All Rights Reserved &copy; 2020 <a href="https://uandiprogramming.blogspot.com" target="_blank" class="text-white text-decoration-none">uandiprogramming</a></p>
  </div>
</div>

app/views/pages/explore.html.erb
<div class="row">
  <div class="col-sm-3">
    <% if user_signed_in? %>
      <div class="card border-0" style="width: 100%;">
        <%= image_tag('profile-banner', class: 'card-img-top')%>
        <div class="card-body d-flex p-0 pt-2 ml-3 profile-info">
          <div class="ml-4 mr-2 mt-1">
            <%= gravatar_for(current_user)%>
          </div>
          <div class="profile-username">
            <p class="my-0"><%= current_user.username%></p>
            <p><%= current_user.username%></p>
          </div>
        </div>
        <div class="card-footer profile d-flex justify-content-between">
          <div>Smart Ideas <br>
            <h6>18</h6>
          </div>
          <div>Followers <br>
            <h6>10.8K</h6>
          </div>
        </div>
      </div>
    <% end %>

    <div class="card">
      <div class="card-body">
        <h2 class="lead">Explore</h2>
        <p class="text-muted">
          This page aggregates smart ideas from ALL Smart Idea Users. It allows you to find and follow new poeple, and your ideas will also apper here so that other poeple can see your ideas and interests and follow you if they chose.
        </p>
      </div>
    </div>
  </div>

  <div class="col-sm-6">
      <%= add_new_post %>
      <% @posts.each do |post| %>
          <div class="card mb-3">
            <div class="card-body">
              <div class="row">
                <div class="col-1 p-1 mr-4">
                  <figure>
                    <%= gravatar_for(post.user) %>
                  </figure>
                </div>
                <div class="col-10 p-2">
                  <p class="post-title">
                    <span class="author font-weight-bold"><%= post.user.username %></span>
                    - <span class="created-at text-muted"><%= post.created_at.to_formatted_s(:short) %></span>
                  </p>
                  <p class="post-content"><%= post.content %></p>
                </div>
                <div class="col-12">
                  <p class="post-links">
                    <i class="fas fa-comments g-links"></i>
                    <i class="fas fa-retweet g-links"></i>
                    <i class="fas fa-heart g-links"></i>
                    <i class="fas fa-cloud-upload-alt g-links"></i>
                  </p>
                </div>
              </div>
            </div>
          </div>  
      <% end %>
    </div>
    <% if user_signed_in? %>
      <div class="col-sm-3">
        <div class="card mb-3">
          <div class="card-header">
            Who To Follow
          </div>
          <ul class="list-group list-group-flush">
            <% @toFollow.each do |follow|%>
                <%= link_to profile_path(follow.username), class: 'text-decoration-none' do %>
                  <div class= "list-group-item d-flex">
                  <figure class="mr-3 mt-2">
                          <%= gravatar_for(follow) %>
                        </figure>
                    <span class="mt-3 text-decoration-none font-weight-600 text-dark">
                      @<%= follow.username %>
                    </span>
                  </div>
                <% end %>
            <% end %>
          </ul>
        </div>
        <div class="card">
          <div class="card-body">
            <p>about</p>
          </div>
        </div>
      </div>
    <% end %>
</div>

<%# Trends %>
<div class="row mt-2">
  <div class="col-sm-3">
  </div>
</div>

<%# Back to the top %>
<div class="row">
  <div class="col-12 text-center">
    <a href="#top" class="text-decoration-none text-muted">Back to the top <i class="fas fa-arrow-up"></i></a>
  </div>
</div>
<div class="col-12 text-center text-muted  mx-0 mt-5">
    <p>All Rights Reserved &copy; 2020 <a href="https://uandiprogramming.blogspot.com" target="_blank" class="text-muted text-decoration-none">uandiprogramming</a></p>
</div>

app/views/pages/home.html.erb
<div class="row" id="top">
  <div class="col-sm-3">
    <% if user_signed_in? %>
      <div class="card border-0" style="width: 100%;">
        <%= image_tag('profile-banner', class: 'card-img-top')%>
        <div class="card-body d-flex p-0 pt-2 ml-3 profile-info">
          <div class="ml-4 mr-2 mt-1">
            <%= gravatar_for(current_user)%>
          </div>
          <div class="profile-username">
            <p class="my-0"><%= current_user.username%></p>
            <p><%= current_user.username%></p>
          </div>
        </div>
        <div class="card-footer profile d-flex justify-content-between">
          <div>Smart Ideas <br>
            <h6><%= current_user.posts.count %></h6>
          </div>
          <div>Followers <br>
            <h6><%= current_user.followers.count %></h6>
          </div>
        </div>
      </div>
    <% end %>

    <div class="card">
      <div class="card-body">
        <h2 class="lead">Smart Idea</h2>
        <p class="text-muted">
          Smart Idea lets you find and follow new poeple, see ideas from poeple around the globe. Your ideas will also apper here so that other poeple can see your ideas and interests and follow you if they are interested.
        </p>
      </div>
    </div>
  </div>

  <div class="col-sm-6">
      <%= add_new_post %>
      <% @posts.each do |post| %>
          <div class="card mb-3">
            <div class="card-body">
              <div class="row">
                <div class="col-1 p-1 mr-4">
                  <figure>
                    <%= gravatar_for(post.user) %>
                  </figure>
                </div>
                <div class="col-10 p-2">
                  <p class="post-title">
                    <span class="author font-weight-bold"><%= post.user.username %></span>
                    - <span class="created-at text-muted"><%= post.created_at.to_formatted_s(:short) %></span>
                  </p>
                  <p class="post-content"><%= post.content %></p>
                </div>
                <div class="col-12">
                  <p class="post-links">
                    <i class="fas fa-comments g-links"></i>
                    <i class="fas fa-retweet g-links"></i>
                    <i class="fas fa-heart g-links"></i>
                    <i class="fas fa-cloud-upload-alt g-links"></i>
                  </p>
                </div>
              </div>
            </div>
          </div>  
      <% end %>
    </div>
  <div class="col-sm-3">
    <div class="card">
      <div class="card-body">
        <p>about</p>
      </div>
    </div>
  </div>
</div>

<%# Trends %>
<div class="row mt-2">
  <div class="col-sm-3">
  </div>
</div>

<%# Back to the top %>
<div class="row">
  <div class="col-12 text-center">
    <a href="#top" class="text-decoration-none text-muted">Back to the top <i class="fas fa-arrow-up"></i></a>
  </div>
</div>
<div class="col-12 text-center text-muted  mx-0 mt-5">
    <p>All Rights Reserved &copy; 2020 <a href="https://uandiprogramming.blogspot.com" target="_blank" class="text-muted text-decoration-none">uandiprogramming</a></p>
</div>

app/views/pages/index.html.erb
<%= landing_page %>

app/views/pages/profile.html.erb
<%# Second row %>
<div class="row">
  <div class="col-sm-3">
    <% if @user_profile %>
      <div class="card border-0" style="width: 100%;">
        <%= image_tag('profile-banner', class: 'card-img-top')%>
        <div class="card-body d-flex p-0 pt-2 ml-3 profile-info">
          <div class="ml-5 pl-4 mr-2 mt-1">
            <%= gravatar_for(@user_profile)%>
          </div>
          <div class="profile-username">
            <p class="my-0"><%= @user_profile.username%></p>
            <p>@<%= @user_profile.username%></p>
          </div>
        </div>
        <div class="card-footer profile d-flex justify-content-between">
          <div>Smart Ideas <br>
            <h6>18</h6>
          </div>
          <div>Followers <br>
            <h6>10.8K</h6>
          </div>
        </div>
      </div>
    <% end %>
  </div>

 
  <div class="col-sm-6">
      <%= add_new_post %>
      <% @posts.each do |post| %>
          <div class="card mb-3">
            <div class="card-body">
              <div class="row">
                <div class="col-1 p-1 mr-4">
                  <figure>
                    <%= gravatar_for(post.user) %>
                  </figure>
                </div>
                <div class="col-10 p-2">
                  <p class="post-title">
                    <span class="author font-weight-bold"><%= post.user.username %></span>
                    - <span class="created-at text-muted"><%= post.created_at.to_formatted_s(:short) %></span>
                  </p>
                  <p class="post-content"><%= post.content %></p>
                </div>
                <div class="col-12">
                  <p class="post-links">
                    <i class="fas fa-comments g-links"></i>
                    <i class="fas fa-retweet g-links"></i>
                    <i class="fas fa-heart g-links"></i>
                    <i class="fas fa-cloud-upload-alt g-links"></i>
                  </p>
                </div>
              </div>
            </div>
          </div>  
      <% end %>
    </div>
  
  <div class="col-sm-3">
  <%= render '/components/follow_button', :user => User.find_by_username(params[:id]) %>
    <div class="card mb-3">
      <div class="card-header">
        Who To Follow
      </div>
      <ul class="list-group list-group-flush">
        <% @toFollow.each do |follow|%>
            <span class="list-group-item">
               @<%= link_to follow.username, profile_path(follow.username), class: 'text-decoration-none font-weight-600 text-dark'%>
            </span>
            
        <% end %>
      </ul>
    </div>

    <div class="card">
      <div class="card-body">
        <p>trends</p>
      </div>
    </div>
  </div>
</div>

<div class="col-12 text-center text-muted  mx-0 mt-5">
    <p>All Rights Reserved &copy; 2020 <a href="https://uandiprogramming.blogspot.com" target="_blank" class="text-muted text-decoration-none">uandiprogramming</a></p>
</div>

app/views/shared/_footer.html.erb
  <div class="col-12 container text-center text-white bg-dark">
    <p>All Rights Reserved &copy; 2020 <a href="https://uandiprogramming.blogspot.com" target="_blank" class="text-white text-decoration-none">uandiprogramming</a></p>
  </div>